"""Neony DOM tree builder.

Build type-safe HTML trees with inline CSS styles, then render them to strings.

Example::

    from neony.dom import Body, Div, Span, Styles, Color

    tree = Body(
        styles=Styles(background_color=Color(hex="#f0f0f0")),
        container=[
            Div(
                class_="card",
                container=[
                    Span(container=["Hello, world!"]),
                ],
            ),
        ],
    )
    print(tree.build())
"""

from .base import DOMElement
from .bridge import (
    CreatePatch,
    DiffEngine,
    MovePatch,
    Neony,
    PatchMessage,
    RemovePatch,
    ReorderPatch,
    ReplacePatch,
    SetTextPatch,
    UpdateAttrsPatch,
    UpdateStylesPatch,
)
from .css import (
    Animation,
    Border,
    BoxShadow,
    Color,
    Columns,
    Filter,
    KeyFrame,
    KeyFrameStop,
    Props,
    Shadow,
    Styles,
    Transform,
    Transition,
    calc,
    pct,
    px,
)
from .elems import (
    # Headings
    H1,
    H2,
    H3,
    H4,
    H5,
    H6,
    # Inline text
    Anchor,
    Article,
    Aside,
    Audio,
    Blockquote,
    Body,
    Bold,
    # Void elements
    Br,
    Button,
    Canvas,
    Code,
    Datalist,
    Details,
    # Content grouping
    Div,
    Em,
    Fieldset,
    Figcaption,
    Figure,
    Footer,
    # Forms
    Form,
    Head,
    # Semantic
    Header,
    Hr,
    # Document structure
    Html,
    # Other
    IFrame,
    Img,
    Input,
    Italic,
    Label,
    Legend,
    Link,
    ListItem,
    Main,
    Mark,
    Meta,
    Nav,
    Option,
    OrderedList,
    Paragraph,
    Pre,
    Progress,
    Script,
    Section,
    Select,
    Small,
    Source,
    Span,
    Strong,
    Style,
    Sub,
    Summary,
    Sup,
    # Tables
    Table,
    TableBody,
    TableData,
    TableFoot,
    TableHead,
    TableHeader,
    TableRow,
    Textarea,
    Title,
    Underline,
    # Lists
    UnorderedList,
    Video,
)
from .events import DomEvent
from .nodes import NodeDescriptor
from .reactive import Computed, Effect, SharedSignal, Signal, batch, effect, untrack

__all__ = [
    "H1",
    "H2",
    "H3",
    "H4",
    "H5",
    "H6",
    "Anchor",
    "Animation",
    "Article",
    "Aside",
    "Audio",
    "Blockquote",
    "Body",
    "Bold",
    "Border",
    "BoxShadow",
    "Br",
    "Button",
    "Canvas",
    "Code",
    "Color",
    "Columns",
    "Computed",
    "CreatePatch",
    "DOMElement",
    "Datalist",
    "Details",
    "DiffEngine",
    "Div",
    "DomEvent",
    "Effect",
    "Em",
    "Fieldset",
    "Figcaption",
    "Figure",
    "Filter",
    "Footer",
    "Form",
    "Head",
    "Header",
    "Hr",
    "Html",
    "IFrame",
    "Img",
    "Input",
    "Italic",
    "KeyFrame",
    "KeyFrameStop",
    "Label",
    "Legend",
    "Link",
    "ListItem",
    "Main",
    "Mark",
    "Meta",
    "MovePatch",
    "Nav",
    "Neony",
    "NodeDescriptor",
    "Option",
    "OrderedList",
    "Paragraph",
    "PatchMessage",
    "Pre",
    "Progress",
    "Props",
    "RemovePatch",
    "ReorderPatch",
    "ReplacePatch",
    "Script",
    "Section",
    "Select",
    "SetTextPatch",
    "Shadow",
    "SharedSignal",
    "Signal",
    "Small",
    "Source",
    "Span",
    "Strong",
    "Style",
    "Styles",
    "Sub",
    "Summary",
    "Sup",
    "Table",
    "TableBody",
    "TableData",
    "TableFoot",
    "TableHead",
    "TableHeader",
    "TableRow",
    "Textarea",
    "Title",
    "Transform",
    "Transition",
    "Underline",
    "UnorderedList",
    "UpdateAttrsPatch",
    "UpdateStylesPatch",
    "Video",
    "batch",
    "calc",
    "effect",
    "pct",
    "px",
    "untrack",
]
