"""Radio component — custom-styled native radio input.

A :class:`Radio` alone is a single toggle; a :class:`RadioGroup` owns
mutual exclusion (exactly one checked item) and dispatches a group
``change`` carrying the selected item's ``value``.  The native
``name`` is generated by the group so screen readers group options;
Python stays the source of truth for exclusion.
"""

from __future__ import annotations

from typing import Literal, Self

from neony.application.theme import Theme
from neony.dom import Color, Div, DomEvent, Span, Styles, Transition
from neony.dom import Input as _InputElem
from neony.dom import Label as _LabelElem

from .base import Component

_ROW = Styles(
    display="flex",
    align_items="center",
    gap="10px",
    font_size="15px",
    cursor="pointer",
    color=Color(var="--color-text-primary"),
)

_DOT = Styles(
    width="18px",
    height="18px",
    border_radius="50%",
    border="1px solid var(--color-border)",
    background_color=Color(var="--color-surface-raised"),
    appearance="none",
    cursor="pointer",
    flex_shrink="0",
    transition=Transition(duration="0.15s", timing="ease"),
)

_CHECKED_DOT = _DOT.model_copy(
    update={
        "border": "1px solid var(--color-accent)",
        # The inset shadow rounds with the 50% radius — the inner dot
        # needs no pseudo-element.
        "box_shadow": "inset 0 0 0 4px var(--color-accent)",
    }
)

_GROUP_VERTICAL = Styles(display="flex", flex_direction="column", gap="8px")
_GROUP_HORIZONTAL = _GROUP_VERTICAL.model_copy(update={"flex_direction": "row", "flex_wrap": "wrap"})


class Radio(Component):
    #: Event types wired internally (via _bind / custom handlers) —
    #: Component.on() must not wire these again.
    _bound_events: frozenset[str] = frozenset({"change", "focus", "blur"})

    """A single radio option; use inside a :class:`RadioGroup` for
    mutual exclusion.

    - ``radio.checked`` reads / sets state (immediate DOM write, no
      callback)
    - ``radio.value`` is the payload a group's ``change`` carries
      (defaults to the lowercased label)
    - ``on_change(fn)`` fires on user toggles with the new bool
    """

    def __init__(
        self, label: str = "", *, value: str | None = None, checked: bool = False, disabled: bool = False
    ) -> None:
        super().__init__()
        self._checked = checked
        self._disabled = disabled
        self._value = value or label.lower()
        self._focused = False

        self._input = _InputElem(type="radio", checked=checked, disabled=disabled)
        self._label_span = Span(container=[label])
        self._root = _LabelElem(styles=_ROW, container=[self._input, self._label_span])

        self._apply_dot_style()
        self._bind(self._input, "change")
        self._bind(self._input, "focus")
        self._bind(self._input, "blur")

    # ---- state ----

    @property
    def value(self) -> str:
        return self._value

    @property
    def checked(self) -> bool:
        return self._checked

    @checked.setter
    def checked(self, value: bool) -> None:
        self._checked = value
        self._input.checked = value  # immediate write; no callback
        self._apply_dot_style()

    @property
    def label(self) -> str:
        return str(self._label_span.container[0]) if self._label_span.container else ""

    @label.setter
    def label(self, value: str) -> None:
        self._label_span.container = [value]

    @property
    def disabled(self) -> bool:
        return self._disabled

    @disabled.setter
    def disabled(self, value: bool) -> None:
        self._disabled = value
        self._input.disabled = value
        self._root.styles.opacity = 0.5 if value else None

    # ---- internals ----

    def _assign_name(self, name: str) -> None:
        """Give the input a ``name`` (set by RadioGroup so screen
        readers treat the group as one control)."""
        self._input.name = name

    def _apply_dot_style(self) -> None:
        """Sync the visible dot with the checked state."""
        styles = _CHECKED_DOT.model_copy() if self._checked else _DOT.model_copy()
        if self._focused:
            # Compose the focus ring OUTSIDE the inner dot — replacing
            # box_shadow outright would drop the checked dot.
            glow = Theme.focus_glow("accent")
            inner = "inset 0 0 0 4px var(--color-accent)" if self._checked else None
            styles = styles.model_copy(update={"box_shadow": f"{glow}, {inner}" if inner else glow})
        self._input.styles = styles

    # ---- events ----

    async def _on_event(self, event_type: str, event: DomEvent) -> None:
        if event_type == "change":
            self._checked = bool(event.value)
            self._input.checked = self._checked
            self._apply_dot_style()
        elif event_type == "focus":
            self._focused = True
            self._apply_dot_style()
        elif event_type == "blur":
            self._focused = False
            self._apply_dot_style()
        await self._dispatch(event_type, event)


class RadioGroup(Component):
    #: The group dispatches ``change`` itself (item handlers set
    #: ``event.value``) — Component.on() must not wire it again.
    _bound_events: frozenset[str] = frozenset({"change"})

    """A mutually exclusive set of :class:`Radio` options.

    - ``group.value`` reads / sets the selected item's value
      (immediate write, no callback)
    - ``on_change(fn)`` fires on user selections with the value string
    - the first added item starts selected unless ``value`` is given
    """

    def __init__(
        self,
        *items: Radio,
        value: str | None = None,
        disabled: bool = False,
        orientation: Literal["vertical", "horizontal"] = "vertical",
    ) -> None:
        super().__init__()
        self._items: list[Radio] = []
        self._input_keys: dict[str, Radio] = {}  # input element key -> radio
        self._value: str | None = None
        self._disabled = disabled
        self._name = f"neony-radio-{id(self)}"

        self._root = Div(
            styles=_GROUP_VERTICAL if orientation == "vertical" else _GROUP_HORIZONTAL,
            container=[],
        )
        for item in items:
            self.add(item)
        if value is not None:
            self.value = value

    # ---- public API ----

    def add(self, radio: Radio) -> Self:
        """Append an option (chainable)."""
        el = radio.build()
        radio._assign_name(self._name)
        # Attach to the input, not the root: user `change` events target
        # the input element (nearest keyed ancestor) and the label root
        # would need bubble_events to hear them.  Bound via _bind so the
        # base dispatcher sets source == "user" on the group's change.
        self._input_keys[radio._input.key] = radio
        self._bind(radio._input, "change")
        self._items.append(radio)
        self._root.container.append(el)
        if self._value is None:
            # First item starts selected unless a value was given.
            radio.checked = True
            self._value = radio.value
        else:
            radio.checked = radio.value == self._value
        return self

    @property
    def items(self) -> list[Radio]:
        return list(self._items)

    @property
    def selected_key(self) -> str | None:
        """The selected option's value — the primary selection property
        (shared with Sidebar / Tree)."""
        return self._value

    @selected_key.setter
    def selected_key(self, value: str | None) -> None:
        self._value = value
        for item in self._items:
            item.checked = item.value == value

    @property
    def value(self) -> str | None:
        """Alias of :attr:`selected_key` — retained for radio-group
        familiarity; selection components expose ``selected_key``."""
        return self.selected_key

    @value.setter
    def value(self, value: str | None) -> None:
        self.selected_key = value

    @property
    def disabled(self) -> bool:
        return self._disabled

    @disabled.setter
    def disabled(self, value: bool) -> None:
        self._disabled = value
        for item in self._items:
            item.disabled = value

    # ---- internals ----

    async def _on_event(self, event_type: str, event: DomEvent) -> None:
        # The base dispatcher routes each radio's `change` here via the
        # input's key (source is already "user") — identify which radio
        # and forward its value.
        radio = self._input_keys.get(event.key)
        if radio is not None and event_type == "change":
            self.value = radio.value
            event.value = radio.value
        await self._dispatch(event_type, event)
